print('{:=^21}'.format('Desafio 009'))
#Tabuada
tabuada = int(input('Digite um numero para saber sua tabuada: '))
print('==== Tabuada de {} ===='.format(tabuada))
print('{} X {:2} = {:2}'.format(tabuada, 1, tabuada*1))
print('{} X {:2} = {:2}'.format(tabuada, 2, tabuada*2))
print('{} X {:2} = {:2}'.format(tabuada, 3, tabuada*3))
print('{} X {:2} = {:2}'.format(tabuada, 4, tabuada*4))
print('{} X {:2} = {:2}'.format(tabuada, 5, tabuada*5))
print('{} X {:2} = {:2}'.format(tabuada, 6, tabuada*6))
print('{} X {:2} = {:2}'.format(tabuada, 7, tabuada*7))
print('{} X {:2} = {:2}'.format(tabuada, 8, tabuada*8))
print('{} X {:2} = {:2}'.format(tabuada, 9, tabuada*9))
print('{} X {:2} = {:2}'.format(tabuada, 10, tabuada*10))